### ISSUE TITLE
BUG: incomplete refdocs (Ruby, Java, maybe others?)

### ISSUE THREAD

**Issue by broady** [googleapis/docuploader#18]
**What I did:**

Navigate to:

(Ruby) https://googleapis.dev/ruby/google-cloud-pubsub/latest/Google/Cloud/PubSub.html

(Java) https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/pubsub/v1/Subscriber.Builder.html

**What I saw**

(Ruby) Unlinked references to `Google::Cloud::Config`
![image](https://user-images.githubusercontent.com/24982/61830535-3b625f80-ae20-11e9-959a-36e622893408.png)

(Java) Unlinked references to `com.google.api.gax.core.CredentialsProvider` etc
![image](https://user-images.githubusercontent.com/24982/61830627-78c6ed00-ae20-11e9-90dd-83766059bd5c.png)

**What I expect**

Able to click through to the docs for Cloud::Config, Java's gax, and any other docs for a dependency or transitive dependency.

**Comment by busunkim96** [comment]
@TheRoyalTnetennba Is there a config somewhere that needs to be updated to get the correct references?

**Comment by busunkim96** [comment]
@chingor13 for Java docs

**Comment by broady** [comment]
Python, too:

`google.api_core.client_options.ClientOptions` is not linked.

https://googleapis.dev/python/language/latest/gapic/v1/api.html#google.cloud.language_v1.LanguageServiceClient

![image](https://user-images.githubusercontent.com/24982/62416418-4cb12600-b5ef-11e9-851c-fce1fd494c3f.png)

**Comment by JustinBeckwith** [comment]
Just to make sure I understand the underlying issue - @busunkim96 is this a bug with docuploader,  or a doc with the individual ref doc generators?  If it's the latter, we should open up bugs in the `google-cloud-<lang>` repos instead of tracking it here.

**Comment by busunkim96** [comment]
@JustinBeckwith It should be corrected in individual ref doc generation

**Comment by busunkim96** [comment]
Opened issues in Python, Java, and Ruby to track.

**Comment by dazuma** [comment]
A note on this. In some cases (Ruby for example) it is in fact very difficult to link some of these references because the class referenced is defined in a different library, and the doc generator is not equipped to create cross-library reference links. (In Ruby, for example, `Google::Cloud::Config` is defined in the `google-cloud-core` library, not in the pubsub library.) It may be technically possible to create links for these, but only to do so manually (by hard-coding the link) which (1) is probably not worth the effort, (2) will obfuscate the code comments from which the docs are being generated, and (3) is pretty much never done for other libraries in the community in which this occurs.
